version: '3'
services:
  backend:
    image: amitchoudhary001/backend:latest
    container_name: backend
    ports:
      - "5000:5000"
    networks:
      - frontend-backend-network

  frontend:
    image: amitchoudhary001/frontend:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend-backend-network

networks:
  frontend-backend-network:
    driver: bridge
